development:
    adapter: postgresql
    database: postgres
    host: postgres

test:
    adapter: postgresql
    database: postgres
    host: postgres

production:
    adapter: postgresql
    database: postgres
    host: postgres
