development:
    adapter: postgresql
    database: depo_rails_db
    host: localhost

test:
    adapter: postgresql
    database: depo_rails_db
    host: localhost

production:
    adapter: postgresql
    database: depo_rails_db
    host: localhost
